# xfburn
# Autogenerated from man page /usr/share/man/man1/xfburn.1.gz
complete -c xfburn -l burn-image --description 'to immediately show the burn image dialog.'
complete -c xfburn -l data-composition --description 'or the.'
complete -c xfburn -l audio-composition --description 'options is specified, then xfburns main window will open up with the selected…'
complete -c xfburn -s '?' -l help --description '.'
complete -c xfburn -s V -l version --description '.'
complete -c xfburn -s i --description '.'
complete -c xfburn -s b -l blank --description '.'
complete -c xfburn -s d --description '.'
complete -c xfburn -s a --description '.'
complete -c xfburn -s t -l transcoder --description '.'
complete -c xfburn -s m -l main --description '.'
complete -c xfburn -l display --description '.'

