# xfce4-sensors
# Autogenerated from man page /usr/share/man/man1/xfce4-sensors.1.gz
complete -c xfce4-sensors -s h -l help --description 'display a short help text.'
complete -c xfce4-sensors -s l -l license --description 'print license information.'
complete -c xfce4-sensors -s V -l version --description 'print version information AUTHOR Fabian Nowak <timystery@arcor. de>.'

