# xfce4-screenshooter
# Autogenerated from man page /usr/share/man/man1/xfce4-screenshooter.1.gz
complete -c xfce4-screenshooter -s h -l help --description 'Show help options.'
complete -c xfce4-screenshooter -l help-all --description 'Show all help options.'
complete -c xfce4-screenshooter -l help-gtk --description 'Show GTK+ Options . SS "Application Options:".'
complete -c xfce4-screenshooter -s c -l clipboard --description 'Copy the screenshot to the clipboard.'
complete -c xfce4-screenshooter -s d -l delay --description 'Delay in seconds before taking the screenshot.'
complete -c xfce4-screenshooter -s f -l fullscreen --description 'Take a screenshot of the entire screen.'
complete -c xfce4-screenshooter -s m -l mouse --description 'Display the mouse on the screenshot.'
complete -c xfce4-screenshooter -s o -l open --description 'Application to open the screenshot.'
complete -c xfce4-screenshooter -s r -l region --description 'Select a region to be captured by clicking a point of the screen without rele…'
complete -c xfce4-screenshooter -s s -l save --description 'Directory where the screenshot will be saved.'
complete -c xfce4-screenshooter -s i -l imgur --description 'Host the screenshot on Imgur, a free online image hosting service.'
complete -c xfce4-screenshooter -s V -l version --description 'Version information.'
complete -c xfce4-screenshooter -s w -l window --description 'Take a screenshot of the active window.'
complete -c xfce4-screenshooter -l display --description 'X display to use SEE ALSO The full documentation for xfce4-screenshooter is m…'

